####
//http://localhost:3000/api/usuarios/
//http://localhost:3000/api/usuarios?desde=10
GET http://localhost:4000/api/usuarios



###
POST http://localhost:4000/api/usuarios
Content-Type: application/json

{
	"nombres": "Piero",
    "apellidos":"Alvarado",
    "documentoDeIdentidad":"0706735445",
    "numeroDeCelular": "0982703085",
    "email":"piero@gmail.com",
    "password":"12345",
    "esAdmin":true
}
# http://localhost:4000/api/upload/usuarios/60dcc5c2958f7d1a98b357ad
###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email":"piero@gmail.com",
    "password":"123456"
}


###
PUT http://localhost:4000/api/usuarios/60db782d5d9a283b48a108bd
Content-Type: application/json
Authorization: x-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGRiNzgyZDVkOWEyODNiNDhhMTA4YmQiLCJpYXQiOjE2MjQ5OTY1NjgsImV4cCI6MTYyNTA4Mjk2OH0.Q4rs8VQKUpSkORSRNMsvfe7Jtfj3twRevzg03C1iG3k

{
	"nombres": "Samantha del Cisne",
    "apellidos":"gonzalez Herrera",
    "email":"samantha@gmail.com",
}

###
//lista todas las ofertas
GET http://localhost:4000/api/oferta

# listar todas las ofertas creadas por un usuario
###
GET http://localhost:4000/api/oferta/usuario/60dcc5c2958f7d1a98b357ad

###
GET http://localhost:4000/api/oferta/busqueda/categoria/Fontaneria


###
GET http://localhost:4000/api/oferta/60dcb8a0df26ce2b7477d26b

###
GET http://localhost:4000/api/oferta/usuario/get-ofertas/60ec6703907adc272c743092

###
POST http://localhost:4000/api/usuarios/validar/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTA0YTJlMjUwMWM4MjQzOTQwZmY1ZDAiLCJpYXQiOjE2MjgwODE3NzAsImV4cCI6MTYyODE2ODE3MH0.2NazSmiA6D7gkzpzwp8WJfocgoAK4RoyMDrl_pcRIa0"
}